<a href="https://colab.research.google.com/github/Ritik4259/Neural-Network-from-scratch/blob/main/backProp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## Backprop on single neuron

In [ ]:
w = np.array([-3.0,-1.0,2.0])
bias = 1.0

inputs = np.array([1.0,0.8,2.6])

target_output = 0.0
learning_rate = 0.001

def relu(x):
    return np.maximum(0.0,x)

def relu_derivative(x):
    return 1 if relu(x)==x else 0

for iteration in range(20000):
    linear_output = np.dot(w,inputs) + bias
    output = relu(linear_output)
    loss = (output - target_output)**2

    dloss_doutput = 2 * (output-target_output)
    doutput_dlinear = relu_derivative(linear_output)
    dlinear_weights = inputs
    dlinear_dbias = 1.0

    dloss_dw = dloss_doutput*doutput_dlinear*dlinear_weights
    dloss_db = dloss_doutput*doutput_dlinear*dlinear_dbias

    w-= learning_rate*dloss_dw
    bias-= learning_rate*dloss_db

    print(f"Iteration: {iteration+1},loss: {loss}")

print(f"Final weight: {w}")
print(f"Final bias:{bias}")



Iteration: 1,loss: 5.760000000000002
Iteration: 2,loss: 5.545459814399998
Iteration: 3,loss: 5.338910512695362
Iteration: 4,loss: 5.140054461949623
Iteration: 5,loss: 4.948605115029348
Iteration: 6,loss: 4.764286597696101
Iteration: 7,loss: 4.586833311077817
Iteration: 8,loss: 4.415989548946759
Iteration: 9,loss: 4.251509129252542
Iteration: 10,loss: 4.09315503937929
Iteration: 11,loss: 3.9406990946157463
Iteration: 12,loss: 3.7939216093461945
Iteration: 13,loss: 3.6526110804883865
Iteration: 14,loss: 3.5165638827223136
Iteration: 15,loss: 3.385583975070664
Iteration: 16,loss: 3.2594826184081565
Iteration: 17,loss: 3.1380781034926586
Iteration: 18,loss: 3.0211954891262347
Iteration: 19,loss: 2.9086663500687653
Iteration: 20,loss: 2.8003285343409443
Iteration: 21,loss: 2.696025929566904
Iteration: 22,loss: 2.595608238019737
Iteration: 23,loss: 2.498930760045838
Iteration: 24,loss: 2.405854185555944
Iteration: 25,loss: 2.316244393282383
Iteration: 26,loss: 2.229972257513327
Iteration: 27

## Back Prop a layer

In [ ]:
inputs = np.array([1,0.5,4,3])

w = np.array([
    [1,0.4,2,0.3],
    [0.4,0.8,4,2],
    [4,1,5,3]
])

b = np.array([0.4,5,3])

learning_rate = 0.001
target_output = 0

def relu(x):
    return np.maximum(x,0)

def relu_derivative(x):
    return (x > 0).astype(float)

for iteration in range(2000):
    z = np.dot(w,inputs) + b
    a = relu(z)

    loss = np.sum((a - target_output)**2)
    dL_da = 2*(a - target_output)
    #dy_da = np.ones_like(a) # y = sum(a-target) dy/da = 1
    da_dz = relu_derivative(z)

    dL_dz = dL_da*da_dz

    dz_dw = inputs

    dL_dw = np.outer(dL_dz,dz_dw)
    dL_db = dL_dz

    w-= learning_rate*dL_dw
    b-= learning_rate*dL_db

    print(f"Iteration {iteration+1}, Loss: {loss}")

print(f"Final weight: {w}")
print(f"Final bias: {b}")



Iteration 1, Loss: 2215.3399999999997
Iteration 2, Loss: 1980.4480536350002
Iteration 3, Loss: 1770.4616416200943
Iteration 4, Loss: 1582.7400363745264
Iteration 5, Loss: 1414.9225060027445
Iteration 6, Loss: 1264.8986264219
Iteration 7, Loss: 1130.7817412870427
Iteration 8, Loss: 1010.8852359538126
Iteration 9, Loss: 903.7013271069386
Iteration 10, Loss: 807.8821013191217
Iteration 11, Loss: 722.2225640867805
Iteration 12, Loss: 645.6454861723004
Iteration 13, Loss: 577.1878566848227
Iteration 14, Loss: 515.9887725374953
Iteration 15, Loss: 461.27861198253777
Iteration 16, Loss: 412.3693560736823
Iteration 17, Loss: 368.6459363415288
Iteration 18, Loss: 329.5584998727205
Iteration 19, Loss: 294.6154945208409
Iteration 20, Loss: 263.3774872906698
Iteration 21, Loss: 235.4516381576119
Iteration 22, Loss: 210.48675982666987
Iteration 23, Loss: 188.16890130393801
Iteration 24, Loss: 168.21739974090679
Iteration 25, Loss: 150.38135090072836
Iteration 26, Loss: 134.43645386006182
Iteration 

## Gradient of loss wrt weights

In [ ]:
dL_dz = np.array([[1., 1., 1.],
 [2., 2., 2.],
 [3., 3., 3.]])

inputs = np.array([[1, 2, 3, 2.5],
 [2., 5., -1., 2],
 [-1.5, 2.7, 3.3, -0.8]])

dL_dw = np.dot(inputs.T,dL_dz)
print(dL_dw)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


## Gradient of loss wrt biases

In [ ]:
biases = np.array([[2, 3, 0.5]])

dL_db = np.sum(dL_dz,axis=0,keepdims=True)
print(dL_db)

[[6. 6. 6.]]


## Gradient of loss wrt inputs

In [ ]:
w = np.array([
    [0.2,0.5,-0.26],
    [0.8,-0.91,-0.27],
    [-0.5,0.26,0.17],
    [1,-0.5,0.87]
]
)

dL_dinput = np.dot(dL_dz,w.T)
print(dL_dinput)

[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]


## Loss function backprop

In [ ]:
class Loss:
  def caculate(self,output,y):
    sample_loss = self.forward(output,y)
    data_loss = np.mean(sample_loss)

    return data_loss

In [ ]:
class Loss_Cat_Cross_Entropy(Loss):
  def forward(self,y_pred,y_true):
    samples = len(y_pred)

    y_pred_clipped = np.clip(y_pred,1e-7,1-1e-7)

    if len(y_true.shape)==1:
      correct_confidences = y_pred_clipped[range(samples),y_true]
    elif len(y_true.shape)==2:
      correct_confidences = np.sum(
          y_pred*y_pred_clipped,
          axis=1
      )

    neg_log_likelihood = -np.log(correct_confidences)
    return neg_log_likelihood

  def backward(self,y_pred,y_true):
    samples = len(y_pred)

    labels = len(y_pred[0])

    if len(y_true.shape)==1:
      y_true = np.eye(labels)[y_true]

    self.dL_dy = -y_true/y_pred

    self.dL_dy = self.dL_dy/samples

## Softmax classifier - combined Softmax activation and cross-entropy loss for faster backward step


In [ ]:
class Activation_softmax:
    def forward(self,inputs):
        exp_vals = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
        prob = exp_vals/np.sum(exp_vals,axis=1,keepdims=True)
        self.output = prob

In [ ]:
class Activation_softmax_Loss_Cat_Cross:
  def __init__(self):
    self.activation = Activation_softmax()
    self.loss = Loss_Cat_Cross_Entropy()

  def forward(self,inputs,y_true):
    self.activation.forward(inputs)
    self.output = self.activation.output

    return self.loss.calculate(self.output,y_true)

  def backward(self,y_pred,y_true):
    samples = len(y_pred)

    if len(y_true.shape)==2:
      y_true = np.argmax(y_true,axis=1)

    self.dinputs = y_pred.copy()  # dinputs = derivative of the loss with respect to the inputs of that layer
    self.dinputs[range(samples),y_true]-=1

    self.dinputs = self.y/samples

## Complete code with forward and backward propagation

In [ ]:
class Layer_Dense:
  def __init__(self,n_input,n_neurons):
    self.weight = np.random.randn(n_input,n_neurons) * np.sqrt(2/n_input)
    self.bias = np.zeros((1,n_neurons))

  def forward(self,inputs):
    self.output = np.dot(inputs,self.weight) + self.bias

  def backward(self):
    pass

In [ ]:
class Activation_ReLu:
  def forward(self,inputs):
    self.output = np.maximum(0,inputs)

In [ ]:
class Activation_softmax:
    def forward(self,inputs):
        exp_vals = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
        prob = exp_vals/np.sum(exp_vals,axis=1,keepdims=True)
        self.output = prob

In [ ]:
class Activation_softmax_Loss_Cat_Cross:
  def __init__(self):
    self.activation = Activation_softmax()
    self.loss = Loss_Cat_Cross_Entropy()

  def forward(self,inputs,y_true):
    self.activation.forward(inputs)
    self.output = self.activation.output

    return self.loss.calculate(self.output,y_true)

  def backward(self,y_pred,y_true):
    samples = len(y_pred)

    if len(y_true.shape)==2:
      y_true = np.argmax(y_true,axis=1)

    self.dinputs = y_pred.copy()  # dinputs = derivative of the loss with respect to the inputs of that layer
    self.dinputs[range(samples),y_true]-=1

    self.dinputs = self.y/samples